version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:5
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: dd
      MYSQL_ROOT_PASSWORD: root
  build:
    container_name: build
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_IP: mysql
      DB_NAME: dd

volumes:
  db_vol:

