version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:5
    hostname: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: dd
      MYSQL_ROOT_PASSWORD: root

  java-app:
    container_name: dd
    hostname: dd
    build:
      context: ./build
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_IP: mysql
      DB_NAME: dd

volumes:
  mysql_data:

